#!/usr/bin/env python

primer_list = list()

primer_dict = {
"R":["A","G"],
"Y":["C","T"],
"S":["G","C"],
"W":["A","T"],
"K":["G","T"],
"M":["A","C"],
"B":["C","G","T"],
"D":["A","G","T"],
"H":["A","C","T"],
"V":["A","C","G"],
"N":["A","T","C","G"],
".":[" "],
"-":[" "] 
}
primer_string = list()
primer_string.append("DTTTCTACTATTTATGARATTCC")
primer_string.append("GCDATGTTTTGTAATGTTG")

def explode(p_primer_string):
	found_count = 0
	for from_char in primer_dict:
		if (p_primer_string.find(from_char) != -1):
			found_count = found_count + 1
	if ( found_count == 0 ):
		primer_list.append(p_primer_string)
	else:
		for from_char in primer_dict:
			if ( p_primer_string.find(from_char) != -1):
				for to_char in primer_dict[from_char]:
					explode(p_primer_string.replace(from_char,to_char,1))	



my_seq = list()
my_seq.append("GGGAGTGGTAATATTTCTTTTATTCATTTAACATATGTGCCAAGTCCCGCTGGAATTAATGAGCAAAAATCTAAACCTACTCAACAAAGTGTTAAAACCTTAAATAAAGCAGGTATTTTCCCCGATTTAATTATTGCTAGAAGTTCACAAGTATTGACAGACCAAATCAGAAAAAAAGTGGCAATGTTTTGCAATGTTGAGAGCACTTCTATTATTGACAATGTTGATGTTTCTACTATTTATGAAATTCCTATATCTTTTTATAAGCAGGGTGTACATGAGATTTTAAGCTCTAAGTTAAATATTAAGGTTGATCCAAAAATAGAAGAGCTTTCAAAGCTTGTAGGAGTTATAAAATCTAATTTTTTTGTGCCTAAAAAAATTATTAATATTGCTATTTGTGGTAAATATGCTGAACTTGATGATTCTTATGCATCAATTAGAGAGTCTTTGGTTCATGTTGCAGCCCATTTGGATTTGCTTATTAAAAGCACTTTAATTGATTCTAATGATTTAAATGAGAGCTGTTTAAAAGAGTTTGACGGCATTATTGTTCCTGGCGGCTTTGGAGGCAAAGGATATGAGGGTAAAATTATGGCTATT")

my_seq.append("GGGAGTGATAATATTGCTTTTGTGCACTTAACTTATATCCCAAATCCTGCTGGGATAAATGAGCAAAAGTCTAAGCCTACTCAGCAGAGTGTCAAGACTTTAAATAAAGCTGGCATTTTTCCAGATTTAATTATTGCAAGAAGTTCTCAACTTTTGACAAAGCAGATAAGACAAAAAATAGCAATGTTTTGTAATGTTGATGCTGAGTCCATTGTTGATAATACTGATGTTTCAACTATTTATGAAATACCCATATCTTTTTATAAACAGGGATTACACGAAATTTTGGGTTCAAAATTAAAAATAAATGTTAAACCTAAGGTGGATGGGCTTGAGCGATTAGTAGGTATAATAAAGAGAAATTTTGCCTCTCCTCGTAAAGTTGTCAATATTGCTATTTGTGGTAAATATACTGAGCTTGGTGATTCTTATGCATCAATATTTGAGTCTTTAACCCATGTATCTGCTAATTTAGATCTTTTAGTTAAGACAATTGTAATTGATAGCACTAATTTTGATGAAGGGATGTTAAAGGGTATAGATGGTATAGTAGTGCCTGGTGGATTTGGGGGTAGGGGATATGAAGGTAAAATGCGTGCAATTGTTTCTACTATTTATGAAATTCC")

for my_primer_instance in primer_string:
	primer_list = list()
	explode(my_primer_instance)

	seq_count = 0
	for my_seq_instance in my_seq:
		seq_count = seq_count + 1
		for my_primer in list(set(primer_list)):
			#print my_primer
			match_pos = my_seq_instance.find(my_primer)
			if (match_pos != -1):
				print "found " + my_primer + " at position " + str(match_pos) + " for seq # " + str(seq_count)
